FROM ros-noetic:adaptor

COPY ./99-k4a.rules /etc/udev/rules.d/99-k4a.rules

# Install dependencies for amrl_shared_lib
RUN apt-get update && apt-get install -y \
    libgtest-dev libgoogle-glog-dev cmake build-essential \
    && rm -rf /var/lib/apt/lists/*

# Install dependencies for spot_ros
RUN apt-get update && apt-get install -y \
    python3-tk \
    && rm -rf /var/lib/apt/lists/*

# Install specific protobuf version and Bosdyn packages for spot_ros, bosydn version matches the sdk version onboard spot
ARG BD_VER=4.0.2
RUN pip3 install protobuf==3.20.1 && \
    pip3 install cython empy==3.3.4 virtualenv jetson-stats rosinstall_generator pydot \
    bosdyn-client==$BD_VER \
    bosdyn-mission==$BD_VER \
    bosdyn-api==$BD_VER \
    bosdyn-core==$BD_VER \
    && rm -rf /var/lib/apt/lists/*

# Install dependencies for graph_navigation
RUN apt-get update && apt-get install -y \
    libgoogle-glog-dev libgflags-dev liblua5.1-0-dev \
    && rm -rf /var/lib/apt/lists/*

# Install dependencies for enml
RUN apt-get update && apt-get install -y \
    liblua5.1-dev libeigen3-dev \
    libjpeg8-dev libgoogle-perftools-dev \
    libsuitesparse-dev libblas-dev liblapack-dev libopenmpi-dev \
    libgoogle-glog-dev libgflags-dev libceres-dev libtbb-dev \
    libncurses5-dev libpopt-dev \
    && rm -rf /var/lib/apt/lists/*

# Install dependencies for webviz and robofleet_client
RUN apt-get update && apt-get install -y \
    cmake \
    && rm -rf /var/lib/apt/lists/*

# Install dependencies for k4a_ros
RUN apt-get update && apt-get install -y \
    liblua5.1-0-dev \
    libgflags-dev \
    libgoogle-glog-dev \
    libgoogle-perftools-dev \
    cimg-dev \
    && rm -rf /var/lib/apt/lists/*

# Install dependencies for spot_autonomy
RUN apt-get update && apt-get install -y \
    libgoogle-glog-dev \
    libgflags-dev \
    && rm -rf /var/lib/apt/lists/*

# Switch to Ubuntu 20.04 (Focal) sources temporarily for libsoundio1 installation
RUN cp /etc/apt/sources.list /etc/apt/sources.list.backup && \
    sed -i 's/jammy/focal/g' /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y libsoundio1

RUN wget https://packages.microsoft.com/ubuntu/18.04/multiarch/prod/pool/main/libk/libk4a1.4/libk4a1.4_1.4.2_arm64.deb && \
    wget https://packages.microsoft.com/ubuntu/18.04/multiarch/prod/pool/main/libk/libk4a1.4-dev/libk4a1.4-dev_1.4.2_arm64.deb && \
    wget https://packages.microsoft.com/ubuntu/18.04/multiarch/prod/pool/main/k/k4a-tools/k4a-tools_1.4.2_arm64.deb

RUN echo 'libk4a1.4 libk4a1.4/accepted-eula-hash string 0f5d5c5de396e4fee4c0753a21fee0c1ed726cf0316204edda484f08cb266d76' | debconf-set-selections && \
    echo 'libk4a1.4 libk4a1.4/accept-eula boolean true' | debconf-set-selections && \
    dpkg -i libk4a1.4_1.4.2_arm64.deb && \
    dpkg -i libk4a1.4-dev_1.4.2_arm64.deb && \
    dpkg -i k4a-tools_1.4.2_arm64.deb

# Restore the original sources list for Ubuntu 22.04 (Jammy)
RUN mv /etc/apt/sources.list.backup /etc/apt/sources.list && \
    apt-get update

# Install Miniconda to /opt/miniconda
RUN wget -O Miniconda3-py310_24.7.1-0-Linux-aarch64.sh https://repo.anaconda.com/miniconda/Miniconda3-py310_24.7.1-0-Linux-aarch64.sh && \
    bash Miniconda3-py310_24.7.1-0-Linux-aarch64.sh -b -p /opt/miniconda3 && \
    rm Miniconda3-py310_24.7.1-0-Linux-aarch64.sh && \
    /opt/miniconda3/bin/conda config --set auto_activate_base false

# conda bash completion
RUN /opt/miniconda3/bin/conda install -c conda-forge conda-bash-completion -y

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    cmake libgoogle-glog-dev libgflags-dev libatlas-base-dev libeigen3-dev libsuitesparse-dev && \
    apt-get remove -y libceres-dev libceres2 libeigen3-dev liborocos-kdl-dev liborocos-kdl1.5 && \
    rm -rf /var/lib/apt/lists/*

# cmake TBB Fix (https://github.com/ceres-solver/ceres-solver/issues/669)
RUN cd /usr/include/tbb && \
    wget -O tbb_stddef.h https://raw.githubusercontent.com/oneapi-src/oneTBB/refs/tags/v2021.1.1/include/oneapi/tbb/version.h

# Eigen Installation (https://tttapa.github.io/Pages/Ubuntu/Software-Installation/Eigen3.html)
RUN mkdir -p ~/custom_builds && cd ~/custom_builds && \
    rm -rf /usr/include/eigen3 /usr/include/Eigen /usr/local/include/eigen3 /usr/local/include/Eigen && \
    git clone --single-branch --depth=1 --branch "3.3.7" https://gitlab.com/libeigen/eigen.git && \
    mkdir eigen/build && cd eigen/build && \
    cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="/usr" && \
    make install && \
    cp -r /usr/include/eigen3/* /usr/include/

# Ceres Solver Installation ([repo](https://github.com/ceres-solver/ceres-solver), [fix-issue](https://github.com/ceres-solver/ceres-solver/issues/392), [fix-patch](https://github.com/mystorm16/ceres-solver/commit/17c1d4239984293af7fa1dcfb853d1101e44218c), [installation-guide](http://ceres-solver.org/installation.html#linux))
RUN cd ~/custom_builds && \
    wget https://github.com/ceres-solver/ceres-solver/archive/refs/tags/1.14.0.tar.gz && \
    tar zxf 1.14.0.tar.gz && cd ceres-solver-1.14.0/internal/ceres && \
    sed -i 's/options.max_num_iterations = 300;  \/\/ Cost function is hard./options.max_num_iterations = 50;/' evaluation_callback_test.cc && \
    cd ~/custom_builds && \
    mkdir ceres-bin && cd ceres-bin && \
    cmake ../ceres-solver-1.14.0 && \
    make -j$(nproc) && \
    make test && \
    make install

# liborocos-kdl (c++ library only, not doing python3 part) ([ref](https://github.com/orocos/orocos_kinematics_dynamics/blob/master/orocos_kdl/INSTALL.md#without-catkin))
RUN cd ~/custom_builds && \
    git clone --branch release-1.4 https://github.com/orocos/orocos_kinematics_dynamics.git && \
    cd orocos_kinematics_dynamics/orocos_kdl && \
    mkdir build && cd build && \
    cmake -DCMAKE_BUILD_TYPE=Release .. && \
    make -j$(nproc) && \
    make install && \
    rm -rf /var/lib/apt/lists/*

# libpcl-dev as this also gets uninstalled on removing libeigen3-dev (https://pcl.readthedocs.io/projects/tutorials/en/latest/compiling_pcl_posix.html#stable)
RUN cd ~/custom_builds && \
    wget https://github.com/PointCloudLibrary/pcl/archive/refs/tags/pcl-1.10.0.tar.gz && \
    tar xvf pcl-1.10.0.tar.gz && \
    cd pcl-pcl-1.10.0 && \
    mkdir build && cd build && \
    cmake -DCMAKE_BUILD_TYPE=Release .. && \
    make -j$(nproc) && \
    make install && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /opt/ros && cd /opt/ros && ln -s /root/ros_noetic_build_2204/catkin_ws/devel noetic && cd ~
RUN echo "source /opt/ros/noetic/setup.bash" >> ~/.bashrc