FROM spot_base:latest

# env vars
ENV DEBIAN_FRONTEND=noninteractive
ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8
ENV TZ=America/Chicago
ENV ROS_DISTRO=noetic

ENV DOCKERHOST_PYTHON_VERSION=3.10
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/python${DOCKERHOST_PYTHON_VERSION}/dist-packages/torch
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/python${DOCKERHOST_PYTHON_VERSION}/dist-packages/torch/lib
# ENV Torch_DIR=$Torch_DIR:/usr/local/lib/python${DOCKERHOST_PYTHON_VERSION}/dist-packages/torch/share/cmake/Torch

ENV NVIDIA_VISIBLE_DEVICES=all
ENV NVIDIA_DRIVER_CAPABILITIES=compute,utility
LABEL com.nvidia.volumes.needed="nvidia_driver"

ENV CUDA_HOME=/usr/local/cuda
ENV PATH=${PATH}:${CUDA_HOME}/bin
ENV LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${CUDA_HOME}/lib64
ENV PIP_ROOT_USER_ACTION=ignore
ENV PIP_NO_CACHE_DIR=
ENV PIP_INDEX_URL=http://jetson.webredirect.org/jp6/cu124
ENV PIP_EXTRA_INDEX_URL="https://pypi.org/simple https://pypi.ngc.nvidia.com"
ENV PIP_TRUSTED_HOST="jetson.webredirect.org pypi.ngc.nvidia.com"

RUN apt-get update && apt-get upgrade -y && apt-get autoremove -y && apt-get autoclean -y && apt-get clean -y

# needed for ros1 building
RUN apt-get update && apt-get install -y \
    libboost-all-dev \
    graphviz \
    libboost-thread-dev \
    libboost-system-dev \
    libboost-filesystem-dev \
    libboost-regex-dev \
    libboost-program-options-dev \
    libconsole-bridge-dev \
    libpoco-dev \
    libtinyxml2-dev \
    liblz4-dev \
    libbz2-dev \
    libtinyxml-dev \
    uuid-dev \
    liblog4cxx-dev \
    libgpgme-dev \
    libgtest-dev \
    libcurl4-openssl-dev \
    liborocos-kdl-dev \
    libbullet-dev \
    liburdfdom-headers-dev \
    libsdl1.2-dev \
    libsdl-image1.2-dev \
    libyaml-cpp-dev \
    libpcap-dev \
    libturbojpeg0-dev \
    libpcl-dev \
    liburdfdom-dev \
    libassimp-dev \
    libogre-1.9-dev \
    python3 \
    python3-pip \
    python3-setuptools \
    python3-rosdep2 \
    python3-vcstools \
    python3-empy \
    python3-nose \
    python3-pycryptodome \
    python3-pyqt5.qtsvg \
    python3-pyqt5 \
    python3-sip \
    python3-sip-dev \
    pyqt5-dev \
    python3-defusedxml \
    python3-mock \
    python3-netifaces \
    python3-gnupg \
    python3-numpy \
    python3-psutil \
    python3-sip-dev \
    python3-sip \
    && rm -rf /var/lib/apt/lists/*

## ROS Noetic build
# Fix for log4cxx error
RUN temp_file_path="/usr/include/log4cxx/boost-std-configuration.h" && \
    sed -i 's/#define STD_SHARED_MUTEX_FOUND 1/#define STD_SHARED_MUTEX_FOUND 0/' "$temp_file_path" && \
    sed -i 's/#define Boost_SHARED_MUTEX_FOUND 0/#define Boost_SHARED_MUTEX_FOUND 1/' "$temp_file_path"


COPY ./builder/clone_repos.sh /root/builder/clone_repos.sh
COPY ./builder/patches/* /root/builder/patches/
COPY ./builder/test_nodelets.xml /root/builder/test_nodelets.xml

# Adapted from https://medium.com/@lukas_reisinger/building-ros-noetic-on-ubuntu-22-04-b3ca676c63e7
# Clone and set up ROS Desktop Full repositories
RUN export GIT_TERMINAL_PROMPT=0 && \
    mkdir -p /root/ros_noetic_build_2204/catkin_ws/src && \
    cd /root/ros_noetic_build_2204 && \
    git clone https://github.com/ros-infrastructure/catkin_pkg.git -b 0.5.2 && \
    git clone https://github.com/ros-infrastructure/rospkg.git -b 1.5.0 && \
    cd /root/ros_noetic_build_2204/catkin_ws/src && \
    mv /root/builder/clone_repos.sh . && \
    ./clone_repos.sh || true

# Apply patches
RUN patch_dir="/root/builder/patches" && \
    repo_base_dir="/root/ros_noetic_build_2204/catkin_ws/src" && \
    for patch_file in "$patch_dir"/*.patch; do \
    repo_name=$(basename "$patch_file" .patch); \
    repo_dir="$repo_base_dir/$repo_name"; \
    if [ -d "$repo_dir" ]; then \
    echo "Applying patch $patch_file to $repo_dir"; \
    (cd "$repo_dir" && git apply --ignore-whitespace "$patch_file"); \
    if [ $? -ne 0 ]; then \
    echo "Failed to apply patch $patch_file to $repo_dir"; \
    else \
    echo "Successfully applied patch $patch_file to $repo_dir"; \
    fi; \
    else \
    echo "Repository directory $repo_dir does not exist. Skipping patch $patch_file."; \
    fi; \
    done

RUN rm -rfv /root/ros_noetic_build_2204/catkin_ws/src/ros_comm/clients/ && \
    cd ~/ && git clone https://github.com/rohitdwivedula/ros_comm.git && \
    ln -s /root/ros_comm/clients/ /root/ros_noetic_build_2204/catkin_ws/src/ros_comm/

RUN apt-get update && apt-get install -y libopencv-dev
RUN cd /root/ros_noetic_build_2204/catkin_pkg && python3 setup.py install && cd /root/ros_noetic_build_2204/rospkg && python3 setup.py install && \
    cd /root/ros_noetic_build_2204/catkin_ws && ./src/catkin/bin/catkin_make install -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE=/usr/bin/python3

RUN rosdep init || true 

RUN rosdep update --rosdistro $ROS_DISTRO && \
    rm -rf /var/lib/apt/lists/*

# # # # https://blog.csdn.net/txr152111/article/details/119330981 fix
RUN cd /root/ros_noetic_build_2204/catkin_ws/install/share/test_nodelet_topic_tools && \
    mkdir test && cd test && cp /root/builder/test_nodelets.xml . && chmod 666 test_nodelets.xml && \
    cd /root/ros_noetic_build_2204/catkin_ws/install/share/test_nodelet && \
    cp /root/builder/test_nodelets.xml ./test_nodelet.xml && chmod 666 test_nodelet.xml && cd ~


COPY ./ros_entrypoint.sh /
ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["bash"]